suppress version date in sqlite3
cs50/cli pull request #154
Opened 2023-04-15 13:19 UTC by rongxin-liu

2023-04-15 15:50 UTC, dmalan commented
So the version will also get out of date eventually. Should we just remove `SQLite version.*`?

2023-04-15 16:02 UTC, rongxin-liu commented
I'm neutral about this. Since SQL commands are unlikely to change frequently, not displaying the version number seems fine.

2023-04-15 16:10 UTC, dmalan commented
Per https://github.com/cs50/cli/issues/157, perhaps cleanest to suppress "usage hints" too, a la `python -3`?

2023-04-15 17:23 UTC, rongxin-liu commented
In that case, best to just comment out that particular print statement in source code entirely.

```
      printf(
        "SQLite version %s %.19s\n" /*extra-version-info*/
        "Enter \".help\" for usage hints.\n",
        sqlite3_libversion(), sqlite3_sourceid()
      );
```

2023-04-15 17:27 UTC, dmalan commented
Want to create a `.patch` file that we can include in the repo, which the Dockerfile runs on `shell.c`? And when we update `sqlite3` next, we can ensure the patch still works?

2023-04-15 17:32 UTC, rongxin-liu commented
> Want to create a `.patch` file that we can include in the repo, which the Dockerfile runs on `shell.c`? And when we update `sqlite3` next, we can ensure the patch still works?

How does this work? Could we update the `sed` command in Dockerfile to comment out those lines?

2023-04-15 17:41 UTC, rongxin-liu commented
You mean place the `sed` command inside `.patch` file, `ADD` that script to Dockerfile and then run it during the build process?

2023-04-15 20:52 UTC, dmalan requested changes

2023-04-15 20:52 UTC, dmalan commented on .gitignore
> +!.patch
It _might_ be a convention to call this `shell.c.patch` perhaps?

2023-04-15 20:52 UTC, dmalan commented on .gitignore
> +!.patch
(In which case no need for `.gitignore`.)

2023-04-15 20:52 UTC, dmalan commented on Dockerfile
> +ADD .patch /tmp
I think `COPY` tends to be best, per https://stackoverflow.com/a/24958548. (And what we use elsewhere.)

2023-04-18 13:35 UTC, rongxin-liu reviewed
To summarize, we will now be commenting out the print statement in source code `shell.c` to suppress version number and usage hint. We create a patch and apply it to the newly downloaded shell.c when building the cli image.

2023-04-19 15:30 UTC, merged